spring:
  application:
    name: changgou-service-cannal
  redis:
    database: 0
    host: 192.168.64.64
    port: 6379
canal:
  client:
    instances:
      example:
        host: 192.168.64.64
        port: 11111
        batchSize: 1000
server:
  port: 18083
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
# Redis数据库索引（默认为0）
  #spring.redis.database=0
  # Redis服务器地址
  #spring.redis.host=192.168.0.24
  # Redis服务器连接端口
  #spring.redis.port=6379
  # Redis服务器连接密码（默认为空）
  #spring.redis.password=
  # 连接池最大连接数（使用负值表示没有限制）
  #spring.redis.pool.max-active=200
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #spring.redis.pool.max-wait=-1
  # 连接池中的最大空闲连接
  #spring.redis.pool.max-idle=10
  # 连接池中的最小空闲连接
  #spring.redis.pool.min-idle=0
  # 连接超时时间（毫秒）
  #spring.redis.timeout=1000