server:
  port: 18086
spring:
  application:
    name: changgou_service_pay
  rabbitmq:
    host: 192.168.64.64
  main:
    #当遇到同样名字的时候，是否允许覆盖注册
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#配置hystrix
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolution:
          strategy: SEMAPHORE
#配置微信支付信息,此处需要真实的信息
weixin:
  #应用的ID
  appid: wx8397f8696b538317
  #商户的ID
  partner: 1473426802
  #秘钥
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #支付回调地址
  notifyurl: http://192.168.64.1
mq:
  pay:
    exchange:
      order: exchange.order
    queue:
      order: queue.order
    routing:
      key: queue.order

