server:
  port: 18084
spring:
  application:
    name: changgou-service-search
  data:
    elasticsearch:
      cluster-name: cluster-elasticsearch
      cluster-nodes: 192.168.64.64:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 300000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000